version: "3.3"

services:
  barotrauma:
    container_name: "${API_ID:-barotrauma}"
    image: "yanwk/barotrauma-server:dockerful"
    ports:
      - "${GAMEPORT:-27015}:${GAMEPORT:-27015}/udp"
      - "${RCONPORT:-27016}:${RCONPORT:-27016}/udp"
    volumes:
      - "./volume:/persistence"
    environment:
      DEFAULT_SERVERNAME: "${API_NAME:-Barotrauma Aquatic}"
      DEFAULT_PASSWORD: "${GAMEPASSWORD:-1234}"
      DEFAULT_PUBLICITY: "true"
      DEFAULT_LANGUAGE: "English"
      DEFAULT_OWNER_STEAMNAME: "Nebual"
      DEFAULT_OWNER_STEAMID: "76561197994054424"
