version: "3"
services:
  valheim:
    container_name: valheim
    image: mbround18/valheim:latest
    environment:
      - PORT=2456
      - NAME="Nebtown Yngheim"
      - PASSWORD="1234"
      - TZ=America/Vancouver
      - WORLD=Yngheim
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    volumes:
    - ./saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./server:/home/steam/valheim