version: "3"

services:
  terraria:
    image: beardedio/terraria:tshock-latest
    container_name: "${API_ID:-terraria}"
    environment:
      world: "${SAVENAME:-save}".wld
    ports:
      - "${GAMEPORT:-7777}:${GAMEPORT:-7777}"
    volumes:
      - ./config:/config
